#what d a user provides : 
INPUT = ['AGE','GENDER','ACTIVITY','HEIGHT','WEIGHT','GOAL','SCHEDULE']

#what the AI provides
OUTPUT = ['HEALTH','FOOD','TRAINING','PROGRAM','EAT','AVOID','ADVICE']

#Specify possible parameters for Predicates
#inputs
AGE =['CHILD','TEEN','YOUNGADULT','MIDDLE','OLD']
GENDER =['MALE','FEMALE']
ACTIVITY =['LOW','MEDIUM','HIGH','VERYHIGH']
GOAL =['LOSS','GAIN','GENERAL','MUSCLE','ENDURANCE']
WEIGHT =['UNDER','NORMAL','OVER']

SCHEDULE =['OPEN','FLEXIBLE','BUSY']

#outputs
HEALTH = ['SKINNY','GOOD','FAT','OBESE']
FOOD = ['REDUCE','MAINTAIN','INCREASE']
TRAINING = ['LOW','AVERAGE','HIGH']
PROGRAM = ['PPL','BBB','CIRCUIT','CROSSFIT','YOGA','CARDIO','STRONGLIFTS','ULS']
EAT = ['EGGS','MEAT','FRUITS','PEANUTS','FISH','PASTA','MILK','...']
AVOID = ['FAT','CANNED','HAM','SODA','CANDY','CAKE','....']
ADVICE = ['A1','A2','A3','A4','A5','A6','A7','A8','A9']

#intermidate
BMI = ['LOW','GOOD','HIGH','VERYHIGH']
